branch-defaults:
  master:
    environment: achievely-dev
    group_suffix: null
environment-defaults:
  achievely-dev:
    branch: null
    repository: null
global:
  application_name: achievely
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-central-1::platform/Docker running
    on 64bit Amazon Linux/2.12.11
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
